// Student, Szkoła , Kurs, Wykład
GET /schools

// Dodawanie kursów do szkoły
PUT /schools/:schoolId/courses

// Listowanie kursów w danej szkole, z wyszukiwaniem po nazwie i roku startu
GET /schools/:schoolId/courses/:name/:year

// Dodawanie wykładów do kursów
POST /schools/:schoolID/courses/:courseId/lectures

// Listowanie wykładów w ramach kursu w danej szkole
GET /schools/:schoolId/courses/:courseId/lectures

// Zapisywanie studentów na kurs w danej szkole
POST /schools/:schoolId/courses/:courseId/students
